### ISSUE TITLE
Learning / File Card counter failure

### ISSUE THREAD

**Issue by frithjofhoppe** [CoffeeCodeSwitzerland/Lernkartei_2017#6]
After leaving the subprogram 'Lernen' the position of the last file card hasn't been noticed. By returning, the last word of the file-card-set is shown and the couter counts even if the words doesn't change. By arriving the last number the window only shows a gray background.

**Comment by kruettlip** [comment]
This Issue is not necessary anymore, due to the issue "Learning / automated change of cards' value".
The issue described in the last comment isn't fixed, but replaced due to a misinterpretation.
